# Generated by Django 4.2.11 on 2025-03-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B-'), ('O+', 'O-'), ('AB+', 'AB-')], max_length=5)),
                ('units_needed', models.PositiveIntegerField()),
                ('contact_number', models.CharField(max_length=15)),
                ('hospital_name', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
