# Generated by Django 4.2.11 on 2025-03-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donars', '0003_alter_bloodrequest_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Expired', 'Expired')], default='Pending', max_length=10),
        ),
    ]
